name: Tests

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "0 0 * * SUN"

    workflow_dispatch:

env:
    ODIN_VERSION: dev-2025-10
    
jobs:
    linux-tests:
        name: Tests
        runs-on: ubuntu-22.04
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v2

            - name: Setup
              run: |
                  sudo apt-get update
                  sudo apt-get install git kcov llvm clang
                  git clone https://codeberg.org/tiny386/tiny386
                  curl -L -o odin.tar.gz https://github.com/odin-lang/Odin/releases/download/${ODIN_VERSION}/odin-linux-amd64-${ODIN_VERSION}-05.tar.gz && mkdir odin && tar -xvzf odin.tar.gz -C ./odin --strip-components=1
                  echo "${GITHUB_WORKSPACE}/odin" >> $GITHUB_PATH

            - name: Generate
              run: make -C tiny386 testdata

            - name: Build
              run: make -C tiny386 testbin

            - name: Test
              run: cd tiny386 && kcov --include-path=src --exclude-path=src/frontend/libretro,src/tests kcov-out ./tests .

            - name: Report
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: bash <(curl -s https://codecov.io/bash) -s kcov-out
